AUTHENTICATION_SOURCES = ['oauth2', 'internal']

OAUTH2_CONFIG = [
    {
        'OAUTH2_NAME': 'gitlab',
        'OAUTH2_DISPLAY_NAME': 'Gitlab',
        'OAUTH2_CLIENT_ID': 'my-client-id-here',
        'OAUTH2_CLIENT_SECRET': 'my-client-secret-here',
        'OAUTH2_TOKEN_URL': 'https://gitlab.com/oauth/token',
        'OAUTH2_AUTHORIZATION_URL': "https://gitlab.com/oauth/authorize",
        'OAUTH2_API_BASE_URL': 'https://gitlab.com/oauth/',
        'OAUTH2_USERINFO_ENDPOINT': 'userinfo',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_ICON': 'fa-gitlab',
        'OAUTH2_BUTTON_COLOR': '#E24329',
    }
]
OAUTH2_AUTO_CREATE_USER = True
